---
name: Ganja
version: 1.0
api: 5.0.0
depend:
  - DEVirion
authors: [Warro, DidntPot]
main: Warro\Base
permissions:
  gb.command.rank:
    default: op
  gb.command.nick:
    default: op
  gb.command.kill:
    default: true
  gb.command.ping:
    default: true
  gb.command.rekit:
    default: true
  gb.command.spawn:
    default: true
...